from .base import ONE_NIGHT_WEREWOLF_RULES
from .common import REFLECTION_SYSTEM_PROMPT, REACTION_SYSTEM_PROMPT
from .gm import (
    GM_COMMENT_SYSTEM_PROMPT,
    GM_MATURITY_SYSTEM_PROMPT,
    GM_COMMENT_REVIEW_SYSTEM_PROMPT,
    GM_COMMENT_REFINE_SYSTEM_PROMPT,
)
from .player import (
    SPEAK_SYSTEM_PROMPT,
    SPEAK_REVIEW_SYSTEM_PROMPT,
    SPEAK_REFINE_SYSTEM_PROMPT,
)
from .strategy import (
    SEER_STRATEGY_SYSTEM_PROMPT,
    WEREWOLF_STRATEGY_SYSTEM_PROMPT,
    MADMAN_STRATEGY_SYSTEM_PROMPT,
    VILLAGER_STRATEGY_SYSTEM_PROMPT,
    STRATEGY_REVIEW_SYSTEM_PROMPT,
    STRATEGY_REFINE_SYSTEM_PROMPT,
)

__all__ = [
    "ONE_NIGHT_WEREWOLF_RULES",
    "REFLECTION_SYSTEM_PROMPT",
    "REACTION_SYSTEM_PROMPT",
    "GM_COMMENT_SYSTEM_PROMPT",
    "GM_MATURITY_SYSTEM_PROMPT",
    "GM_COMMENT_REVIEW_SYSTEM_PROMPT",
    "GM_COMMENT_REFINE_SYSTEM_PROMPT",
    "SPEAK_SYSTEM_PROMPT",
    "SPEAK_REVIEW_SYSTEM_PROMPT",
    "SPEAK_REFINE_SYSTEM_PROMPT",
    "SEER_STRATEGY_SYSTEM_PROMPT",
    "WEREWOLF_STRATEGY_SYSTEM_PROMPT",
    "MADMAN_STRATEGY_SYSTEM_PROMPT",
    "VILLAGER_STRATEGY_SYSTEM_PROMPT",
    "STRATEGY_REVIEW_SYSTEM_PROMPT",
    "STRATEGY_REFINE_SYSTEM_PROMPT",
]
